config/routes.rb
Rails.application.routes.draw do

	resources :pages, only: [:update, :destroy] do
		collection do
			get :dashboard
		end
	end

	resources :posts do
		resources :comments, only: [:create, :destroy]
	end

	devise_for :users, controllers: {
		sessions: 'users/sessions',
		registrations: 'users/registrations'
	}

	root 'posts#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mi Blog</title>
    <%= csrf_meta_tags %>

    <!--Bootswatch CDN-->
	<link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/lumen/bootstrap.min.css" rel="stylesheet" integrity="sha384-gv0oNvwnqzF6ULI9TVsSmnULNb3zasNysvWwfT/s4l8k5I+g6oFz9dye0wg3rQ2Q" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

	<!--jQuery 3.2.1 minified CDN-->
    <script   src="https://code.jquery.com/jquery-3.2.1.min.js"   integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="   crossorigin="anonymous"></script>

	<!--Bootstrap JS CDN-->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  </head>

  <body>
	  <nav class="navbar navbar-default">
	  <div class="container">
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="<%= root_url %>">
	      	<span class="glyphicon glyphicon-home"></span> Mi Blog
	      </a>
	    </div>

	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav navbar-right">
	        <% if user_signed_in? %>
						<% if current_user.admin? %>
							<li><a href="<%= dashboard_pages_path %>">Dashboard</a></li>
						<% end %>
	        	<li><a href="#">Hola <%= current_user.name %>!</a></li>
	        	<li><%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete %></li>
	        <% else %>
	        	<li><%= link_to 'Inicia sesión', new_user_session_path %></li>
	        	<li><%= link_to 'Regístrate', new_user_registration_path %></li>
	        <% end %>
	      </ul>
	    </div>
	  </div>
	</nav>
    <div class="container">
			<% if alert.present? %>
				<div class="alert"><%= alert %></div>
    	<% end %>
			<%= yield %>
    </div>
  </body>
</html>